name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    if: ${{ hashFiles('backend/requirements.txt') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Lint (ruff) & format check (black)
        run: |
          if [ -f backend/pyproject.toml ]; then \
            pip install ruff black; \
            black --check backend; \
            ruff check backend; \
          fi
      - name: Type check (mypy)
        run: |
          if [ -f backend/pyproject.toml ]; then \
            mypy backend/src; \
          fi
      - name: Run pytest
        run: |
          if [ -d backend/tests ]; then \
            pytest -q --maxfail=1; \
          else \
            echo "No backend tests yet"; \
          fi

  frontend:
    if: ${{ hashFiles('frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install
        working-directory: frontend
        run: npm ci
      - name: Lint
        working-directory: frontend
        run: |
          if [ -f .eslintrc.* ]; then npm run lint --if-present; else echo "No ESLint config yet"; fi
      - name: Test (Vitest)
        working-directory: frontend
        run: npm test --if-present --silent
