name: CI

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - frontend/**
      - .github/workflows/ci.yml
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint (ruff)
        run: cd backend && ruff check src tests || true

      - name: Format check (black)
        run: cd backend && black --check src tests || true

      - name: Type check (mypy)
        run: cd backend && mypy src || true

      - name: Run pytest
        run: cd backend && pytest -v

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint (eslint)
        working-directory: frontend
        run: npm run lint --if-present || true

      - name: Run tests (vitest)
        working-directory: frontend
        run: npm test --if-present
